### ISSUE TITLE
Need to refresh twice to see a change

### ISSUE THREAD

**Issue by filmaj** [adobe/helix-simulator#156] opened 2019-03-06 18:53 UTC
**Description**
When I make a change in e.g. `.htl` file or `.pre.js` file, and am running locally using `hlx up`, I see helix rebuilds my project rather quickly:

```
Rebuilding project files...done 757ms
```

But! I need to refresh _twice_ in my browser (localhost:3000) to see the change.

**Expected behavior**
I should only need to refresh once 😄 

**Version:**
run: `$ hlx --version`
0.13.6

**Comment by stefan-guggisberg** [comment] 2019-03-07 17:28
I can't reproduce. I tried the following:

> node 8.12.0
> hlx 0.13.7 (binary distribution)
> macos 10.14.3
> chrome 72.0.3626.121

```
hlx demo demo
cd demo
code .
hlx up
```

edit and save e.g. `html.htl`:
```
> Rebuilding project files...done 623ms
```

cmd+r in chrome: change is rendered

I tried with both hlx 0.13.7 & 0.13.6. 

@filmaj do you have a different env or are you doing something different?

**Comment by filmaj** [comment] 2019-03-07 17:42
Hmm, I also cannot reproduce using the demo site. However, this is normal with the dev site, and I think I see why. Try this:

```
git clone https://github.com/adobe/developer.adobe.com.git
cd developer.adobe.com
npm install
npm start
```

then edit not the main `html.htl` template, but the "sub-template" `default_html.htl` (we dispatch to this template using an `esi:include` tag inside `html.htl`)

In this case I need to refresh twice.

**Comment by stefan-guggisberg** [comment] 2019-03-07 18:11
Ok, got it. I can reproduce it.

What I noticed:

Without any changes, if the page is rendered the first time I see the following console output:

```
[hlx] warn: Whitelist forbids embedding of URL: https://adobeioruntime.net/api/v1/web/io-solutions/adobe-oauth-playground/oauth.html
request url /index.html
request path /index.html
action path /index.md
action rootPath 
default
no root path
[hlx] warn: Whitelist forbids embedding of URL: https://adobeioruntime.net/api/v1/web/io-solutions/adobe-oauth-playground/oauth.html
processing section with index 0
processing section with index 1
processing section with index 2
processing section with index 3
processing section with index 4
```
If I refresh i get this shorter console output:
```
[hlx] warn: Whitelist forbids embedding of URL: https://adobeioruntime.net/api/v1/web/io-solutions/adobe-oauth-playground/oauth.html
request url /index.html
request path /index.html
action path /index.md
action rootPath 
default
no root path
```

If I refresh repeatedly console output alternates between the long and short versions. Perhaps related?

**Comment by stefan-guggisberg** [comment] 2019-03-08 17:58
Problem was that `nodesi` caches includes and returns stale data while fetching in the background.

Trivial fix but took me a while to nail the little bugger...

**Comment by stefan-guggisberg** [comment] 2019-03-08 17:59
fixed in v2.10.5

**Closed by stefan-guggisberg** 2019-03-08 17:59 UTC

**Comment by stefan-guggisberg** [comment] 2019-03-08 18:24
i released a new `helix-cli` release with the fix: https://github.com/adobe/helix-cli/releases/tag/v0.13.8

**Comment by filmaj** [comment] 2019-03-08 18:26
Hero!!! Thank you Stefan
